### ISSUE TITLE
pyfyre create-app . (will purge all files inside the path)

### ISSUE THREAD

**Issue by mpotane** [pyfyre/pyfyre#16] opened 2022-09-10 14:34 UTC
**Describe the bug**
When creating the app in current working directory "./" it removes all files inside it.

**To Reproduce**
1. python3 -m venv example-app
2. cd example-app
3. source /bin/activate
4. pip install --upgrade pip setuptools pyfyre
5. pyfyre create .

**Expected behavior**
Keep files inside the path

 **Error message**
FileExistError

**Comment by NadieFiind** [comment] 2022-09-22 04:36
That is the expected behavior when you create a project in an existing directory. If `create-app` is run on an existing directory, pyfyre will give you a prompt to overwrite the directory. However, due to a bug, when you create a project in your current directory (`.`, `./`), pyfyre causes unexpected behaviors including the `FileExistError` that you encountered. This however is already fixed on the `main` branch.

I am currently rewriting the entirety of the project. Expect breaking changes.
The `main` branch will soon be the default branch for this repository once the rewrite is done.

**Closed by NadieFiind** 2022-09-22 04:36 UTC

**Comment by NadieFiind** [comment] 2022-10-30 05:52
Just an update about this issue. The PyFyre rewrite has now been released on [PyPI](https://pypi.org/project/pyfyre/). The documentation is not yet updated, we will work on that soon.
